# Generated by Django 5.0.6 on 2024-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='turno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
